project:
  type: website
  resources:
  - "pdf/*.pdf"
  
website:
  title: "    "
  # site-url: https://mroberts1.github.io/digital-culture-sp24/
  # twitter-card:
  #   creator: "@mroberts_vma"
  #   card-style: summary_large_image
  # favicon: "/img/cropped-cropped-flourish-1-270x270.gif"
  # navbar:
  #   background: "#62259d"
  #   search: true
  #   right:
  #     - icon: envelope
  #       aria-label: envelope
  #       href: mailto:martin_roberts@emerson.edu
  #     - icon: mastodon
  #       aria-label: mastodon
  #       href: https://merveilles.town/@dokoissho
  #     - icon: github
  #       aria-label: github
  #       href: https://github.com/mroberts1
  #     - icon: facebook
  #       aria-label: facebook
  #       href: https://facebook.com/mr05301
  #     - icon: twitter
  #       aria-label: twitter
  #       href: https://twitter.com/mroberts_VMA
format:
  html:
    toc: true
    toc-depth: 3
    toc-location: left
    toc-title: '   '
    theme:
      light: ember.scss
      dark: [ember.scss, slate]
    css: custom.scss
    self-contained: false
    grid:
        sidebar-width: 300px
        body-width: 700px
        margin-width: 300px
        gutter-width: 1em
    linestretch: 1.5
    fontsize: 1em
    smooth-scroll: true
    linkcolor: "#62259d"
    link-external-newwindow: true
  # PrettyPDF-pdf: default
fig-responsive: true
image-alt: " "
execute:
  freeze: auto
# reference-location: margin
# citation-location: margin
# editor: visual
